# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Research
    url: "/research/"
    weight: 10
  - name: Papers
    url: "/publications/"
    weight: 20
  - name: Invited Talks
    url: "/invited-talks/"
    weight: 30
  - name: Social Projects
    url: "/social-projects/"
    weight: 40
